version: '3.8'

services:
  web:
    build: ./web
    ports:
      - 3000:3000
    expose:
      - 3000
    restart: unless-stopped
    networks:
      - web-backend
    depends_on:
      - backend
      - supertokens
  
  backend:
    build: ./backend
    ports:
      - 8000:8000
    expose:
      - 8000
    restart: unless-stopped
    networks:
      - web-backend
      - backend-mongo
      - backend-supertokens
      - backend-elasticsearch
      - backend-chroma
    depends_on:
      - mongo
      - supertokens
      - elasticsearch
      - chroma
    environment:
      MONGO_URL: "mongodb://mongo:27017"
      SUPERTOKENS_URL: "http://supertokens:3567"
      WEBSITE_DOMAIN: "http://127.0.0.1:3000"
      API_DOMAIN: "http://127.0.0.1:8000"
      ELASTICSEARCH_URL: "http://elasticsearch:9200"
      ELASTICSEARCH_PASSWORD: "changeme"
      ELASTICSEARCH_USERNAME: "elastic"
      CHROMA_URL: http://chroma:8000
  
  mongo:
    image: mongo:4.0-xenial
    restart: unless-stopped
    networks:
      - backend-mongo
    expose:
      - 27017
    volumes:
      - mongo-data:/data/db
    logging:
      driver: none

  supertokens:
    image: registry.supertokens.io/supertokens/supertokens-mysql:4.2
    depends_on:
      - sql
    expose:
      - 3567
    environment:
      MYSQL_CONNECTION_URI: mysql://supertokens_user:somePassword@sql:3306/supertokens
    networks:
      - supertokens-sql
      - backend-supertokens
    restart:
      unless-stopped
    healthcheck:
      test: >
        bash -c 'exec 3<>/dev/tcp/127.0.0.1/3567 && echo -e "GET /hello HTTP/1.1\r\nhost: 127.0.0.1:3567\r\nConnection: close\r\n\r\n" >&3 && cat <&3 | grep "Hello"'
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: none

  sql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: supertokens_user
      MYSQL_PASSWORD: somePassword 
      MYSQL_DATABASE: supertokens
    expose:
      - 3306
    networks:
      - supertokens-sql
    volumes:
      - sql-data:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    logging:
      driver: none

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.0
    restart: unless-stopped
    expose:
      - 9200
    networks:
      - backend-elasticsearch
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - xpack.security.enabled=false
      - ELASTIC_PASSWORD=changeme
      - ELASTIC_USERNAME=elastic
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    healthcheck:
      test: curl -s http://elasticsearch:9200 >/dev/null || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
    logging:
      driver: none

  chroma:
    build:
      context: https://github.com/chroma-core/chroma.git#0.3.14
    restart: unless-stopped
    expose:
      - 8000
    environment:
      - CHROMA_DB_IMPL=clickhouse
      - CLICKHOUSE_HOST=clickhouse
      - CLICKHOUSE_PORT=8123
    depends_on:
      - clickhouse
    networks:
      - backend-chroma
      - chroma-clickhouse
    command: uvicorn chromadb.app:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - chroma-data:/index_data

  clickhouse:
    image: clickhouse/clickhouse-server:22.9-alpine
    restart: unless-stopped
    expose:
      - 8123
      - 9000
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - CLICKHOUSE_TCP_PORT=9000
      - CLICKHOUSE_HTTP_PORT=8123
    networks:
      - chroma-clickhouse
    volumes:
      - clickhouse-data:/bitnami/clickhouse

volumes:
  mongo-data:
  sql-data:
  elasticsearch-data:
  chroma-data:
  clickhouse-data:

networks:
  web-backend:
  backend-mongo:
  backend-supertokens:
  backend-elasticsearch:
  backend-redis:
  supertokens-sql:
  backend-chroma:
  chroma-clickhouse:
