version: '3.8'

services:
  web:
    build: ./web
    ports:
      - 3000:3000
    expose:
      - 3000
    restart: unless-stopped
    networks:
      - web-backend
    depends_on:
      - backend
    env_file:
      - ./web/src/.env.local
  
  backend:
    build: ./backend
    ports:
      - 8000:8000
    expose:
      - 8000
    restart: unless-stopped
    networks:
      - web-backend
    env_file:
      - ./backend/.env

networks:
  web-backend: